version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Building by Guy...
      - aws cloudformation package --template-file basic-vpc-infrastructure.yml --s3-bucket vpctemp123 --output-template-file outputtemp.yml
      - echo ***template package successfully***
artifacts:
  files:
    - '**/*'